name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Arabic NLP script
        run: python arabic_nlp.py

      - name: Install testing tools
        run: pip install pytest flake8 black

      - name: Run tests
        run: pytest test_arabic_nlp.py

      - name: Lint with flake8
        run: flake8 .

      - name: Check code formatting with Black
        run: black --check .
